# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ansId', models.AutoField(primary_key=True, serialize=False)),
                ('ans_credit', models.CharField(blank=True, choices=[('l', 'low'), ('m', 'middle'), ('h', 'high')], max_length=2)),
                ('ans_time', models.DateField(blank=True)),
                ('user_reply', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('expertId', models.AutoField(primary_key=True, serialize=False)),
                ('exp_acount', models.CharField(max_length=20)),
                ('exp_password', models.CharField(max_length=20)),
                ('exp_mail', models.EmailField(blank=True, max_length=254)),
                ('exp_name', models.CharField(blank=True, max_length=10)),
                ('exp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plantId', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=30)),
                ('plant_image1', models.CharField(blank=True, max_length=150, null=True)),
                ('plant_image2', models.CharField(blank=True, max_length=150, null=True)),
                ('plant_image3', models.CharField(blank=True, max_length=150, null=True)),
                ('other_details', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('que_time', models.CharField(blank=True, max_length=50, null=True)),
                ('imge_other1', models.CharField(blank=True, max_length=150, null=True)),
                ('describe', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_passWd', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('birth', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantData.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='exp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantData.Expert'),
        ),
        migrations.AddField(
            model_name='answer',
            name='pla_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantData.Plant'),
        ),
        migrations.AddField(
            model_name='answer',
            name='que_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantData.Question'),
        ),
    ]
